CREATE TABLE IF NOT EXISTS PATIENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50) NOT NULL,
  BIRTHDAY DATE NOT NULL,
  SECURITY_NUMBER VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS VISIT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ID_PATIENT INT NOT NULL,
  VISIT_DATE DATE NOT NULL,
  VISIT_TYPE VARCHAR(20) NOT NULL,
  VISIT_REASON VARCHAR(20) NOT NULL,
  NOTES VARCHAR(255)
);